// packages/ui-components/src/components/layout/divider/Divider.tsx
/*
 * SPDX-FileCopyrightText: 2021 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import React, { HTMLAttributes } from 'react';
import styled from 'styled-components';

import { getColor } from '../../../theme/theme-utils';
import { AnyColor, MakeRequired, With$Prefix } from '../../../types/utils';

type DividerProps = Omit<HTMLAttributes<HTMLDivElement>, 'color'> & {
	/** Divider color */
	ref?: React.Ref<HTMLDivElement>;
	color?: AnyColor;
};

const DividerEl = styled.div<With$Prefix<MakeRequired<DividerProps, 'color'>>>`
	box-sizing: border-box;
	background-color: ${({ theme, $color }): string => getColor($color, theme)};
	height: 0.0625rem;
	max-height: 0.0625rem;
	min-height: 0.0625rem;
	width: 100%;
`;

const Divider = ({ color = 'gray2', ref, ...rest }: DividerProps) => {
	return <DividerEl $ref={ref} $color={color} data-testid={'divider'} {...rest} />;
};

export { Divider };
export type { DividerProps };

// packages/ui-components/src/web-components/divider-wc.ts
/*
 * SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import './theme.css';

import { css, html, LitElement } from 'lit';
import { property } from 'lit/decorators.js';

export class DividerElement extends LitElement {
  static override styles = css`
    :host {
      display: block;
      width: 100%;
    }
    .divider {
      box-sizing: border-box;
      height: 0.0625rem;
      max-height: 0.0625rem;
      min-height: 0.0625rem;
      width: 100%;
      border: none;
    }
  `;

  @property({ type: String, reflect: true })
  color = 'gray2';

  override render() {
    return html`<hr
      data-testid="divider"
      role="separator"
      style="background-color: var(--color-${this.color});"
      class="divider"
      aria-orientation='horizontal'
    ></hr>`;
  }
}

if (!customElements.get('divider-wc')) {
  customElements.define('divider-wc', DividerElement);
}

declare global {
  interface HTMLElementTagNameMap {
    'divider-wc': DividerElement;
  }
}
