// packages/ui-components/src/web-components/spinner-wc.ts
/*
 * SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import './theme.css';

import { css, html, LitElement } from 'lit';

/**
 * A simple loading spinner web component
 * @element spinner-wc
 */
export class SpinnerWC extends LitElement {
  static override styles = css`
    :host {
      display: inline-block;
    }
    .spinner {
      width: 0.75rem;
      height: 0.75rem;
      border: 0.125rem solid var(--color-primary, #2b73d2);
      border-right-color: transparent;
      border-radius: 50%;
      animation: spinner-rotate 0.75s linear infinite;
    }
    @keyframes spinner-rotate {
      from {
        transform: rotate(0deg);
      }
      to {
        transform: rotate(360deg);
      }
    }
  `;

  override render() {
    return html`
      <div
        data-testid="spinner"
        class="spinner"
        role="status"
        aria-busy="true"
        aria-label="Loading"
      ></div>
    `;
  }
}

if (!customElements.get('spinner-wc')) {
  customElements.define('spinner-wc', SpinnerWC);
}

declare global {
  interface HTMLElementTagNameMap {
    'spinner-wc': SpinnerWC;
  }
}

// packages/ui-components/src/components/basic/Spinner.tsx
/*
 * SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { HTMLAttributes } from 'react';
import styled, { keyframes } from 'styled-components';

import { getColor } from '../../theme/theme-utils';
import { AnyColor } from '../../types/utils';

type SpinnerProps = HTMLAttributes<HTMLDivElement> & {
	color: AnyColor;
};

const rotateKeyframes = keyframes`
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
	}
`;

const StyledSpinner = styled.div<{ $color: AnyColor }>`
	width: 0.75rem;
	height: 0.75rem;
	color: ${({ theme, $color }): string => getColor($color, theme)};
	border: 0.125rem solid currentColor;
	border-right-color: transparent;
	border-radius: 50%;
	animation: ${rotateKeyframes} 0.75s linear infinite;
`;

const Spinner = ({ color, ...rest }: SpinnerProps) => {
	return <StyledSpinner data-testid="spinner" $color={color} {...rest} />;
};

export type { SpinnerProps };
export { Spinner };
